# Generated by Django 3.2.19 on 2023-08-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
