# Generated by Django 4.2.4 on 2023-08-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_add_path_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['my_order'], 'verbose_name_plural': 'Images'},
        ),
        migrations.AddField(
            model_name='placeimage',
            name='my_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
