# Generated by Django 4.2.4 on 2023-08-19 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_use_HTMLField'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='path',
        ),
    ]
