# Generated by Django 4.2.4 on 2023-08-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_remove_place_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
    ]
