# Generated by Django 4.2.4 on 2023-08-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_use_cascade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.FloatField(null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lng',
            field=models.FloatField(null=True, verbose_name='Долгота'),
        ),
    ]
